# NB: this file was automatically generated by Dynare
#     from main.mod
#
function static_params_derivs(y, x, params)
@inbounds begin
T = zeros(0)
rp = zeros(70, 35);
gp = zeros(70, 70, 35);
end
return (rp, gp)
end
